buildVariable: false
familyName: Noto Sans Old Hungarian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 11825
    start: 11825
  - end: 8282
    start: 8282
  - end: 8286
    start: 8285
recipeProvider: noto
sources:
- NotoSansOldHungarian.glyphs
